"""
Django settings for FileMaster project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os

# Chemin de base du projet
BASE_DIR = Path(__file__).resolve().parent.parent

# Clé secrète (à changer en production !)
SECRET_KEY = 'django-insecure-!m&^#*7&^*7&^*7&^*7&^*7&^*7&^*7&^*7&^*7&^*7&^*7&^*7&^*7'

# Mode développement/production
DEBUG = True

# Hôtes autorisés (à configurer en production)
ALLOWED_HOSTS = []

# Applications installées
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.pdf_tools',
    'core.image_tools',
    'core.document_tools',
]

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuration des URLs
ROOT_URLCONF = 'filemaster.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI
WSGI_APPLICATION = 'filemaster.wsgi.application'

# Base de données (SQLite par défaut)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Validation des mots de passe
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalisation
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================
# CONFIGURATION DES FICHIERS STATIQUES ET MÉDIAS
# =============================================

# URL publique pour les fichiers statiques
STATIC_URL = '/static/'

# Dossiers où Django cherche les fichiers statiques en développement
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Dossier pour tes fichiers statiques personnalisés
]

# Dossier où collectstatic copie les fichiers pour la production
STATIC_ROOT = BASE_DIR / "staticfiles"

# URL publique pour les fichiers uploadés
MEDIA_URL = '/media/'

# Dossier où sont stockés les fichiers uploadés
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================
# AUTRES PARAMÈTRES
# =============================================

# Type de champ pour les clés primaires
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Taille maximale des fichiers uploadés (100 Mo)
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100 MB
